name: Check Required Approvals

on:
  pull_request_review:
    types: [submitted]

jobs:
  check-required-approvals:
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      # Install dependencies if necessary
      # - name: Install dependencies
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y jq gh

      - name: Fetch changed files
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Fetching changed files from the pull request..."
          gh pr view ${{ github.event.pull_request.number }} --json files --jq '.files[].path' > changed_files.txt
          echo "Changed files:"
          cat changed_files.txt

      - name: Fetch approval rules
        run: |
          echo "Fetching approval rules..."
          cat .github/approval_rules.json

      - name: Fetch approved reviews from GitHub API
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Fetching latest reviews from GitHub API..."
          gh api repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews > reviews.json

          echo "Processing reviews to get the latest state per reviewer..."
          jq -r 'group_by(.user.login) | map(last) | .[] | select(.state == "APPROVED") | .user.login' reviews.json | sort -u > approved_reviewers.txt

          echo "Approved reviewers list:"
          cat approved_reviewers.txt

      - name: Make script executable
        run: chmod +x ./.github/scripts/check_required_approvals.sh

      - name: Check if all required owners approved
        run: ./.github/scripts/check_required_approvals.sh
